spring:
  application:
    name: api-gateway  # ?????????
  cloud:
    gateway:
      routes:
        - id: driver-management  # ??ID
          uri: lb://driver-management  # ???????lb://??????? driver-management ??
          predicates:
            - Path=/api/driver/**  # ????? /api/driver/ ?????
        - id: passenger-management  # ??ID
          uri: lb://passenger-management  # ???????lb://??????? passenger-management ??
          predicates:
            - Path=/api/passenger/**  # ????? /api/passenger/ ?????
        - id: billing-service  # ??ID
          uri: lb://billing
          predicates:
            - Path=/bill/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
            allowedMethods: "*"
            allowCredentials: true


    discovery:
      enabled: true  # ??????

server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # ?? Eureka Server ???

driver-service:
  base-url: http://localhost:8082
passenger-service:
  base-url: http://localhost:8081
billing-service:
  base-url: http://localhost:8083

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
