
spring:
  application:
    name: passenger-management
  datasource:
    url: jdbc:mysql://localhost:3306/rideservice?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: passenger

server:
  port: 8081

billing-service:
  base-url: http://localhost:8083

driver-service:
  base-url: http://localhost:8082

