spring:
  application:
    name: eureka-server
server:
  port: 8761  # Eureka Server ???

eureka:
  client:
    registerWithEureka: false  # Eureka Server ???????
    fetchRegistry: false  # Eureka Server ??????????????
  server:
    enableSelfPreservation: false  # ?????????????????????????????
