
spring:
  application:
    name: billing
  datasource:
    url: jdbc:mysql://localhost:3306/rideservice?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  cloud:
#    gateway:
#      routes:
#        - id: billing-service
#          uri: lb://billing
#          predicates:
#            - Path=/bill/**
#          filters:
#            - StripPrefix=1
    discovery:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka ????
management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: 8083

driver-service:
  base-url: http://localhost:8082

passenger-service:
  base-url: http://localhost:8081

